from typing import Protocol, Sequence


class PlayerProto(Protocol):
    def get_action(self, game: "GameProto", actions_left: int) -> "Action": ...

    def has_won(self) -> bool: ...


class GameProto(Protocol):
    def play(self) -> PlayerProto: ...
    def get_opposition(self, player: PlayerProto) -> Sequence[PlayerProto]: ...


class Action(Protocol):
    def apply(self, g: GameProto) -> None: ...

    def action_count(self) -> int: ...
